import apiClient from '@/lib/axios';
import { MenuResponse } from '@/types/menu';

// Mock data for offline development
const MOCK_MENU_DATA: MenuResponse = {
  restaurant: {
    id: 'rest_001',
    name: 'Restaurant CommanDex',
    currency: 'FCFA',
    description: 'Premium dining experience',
    address: '123 Restaurant Street',
    phone: '+225 01 02 03 04 05',
  },
  categories: [
    { id: 'cat_001', name: 'Appetizers', order: 1 },
    { id: 'cat_002', name: 'Main Courses', order: 2 },
    { id: 'cat_003', name: 'Desserts', order: 3 },
    { id: 'cat_004', name: 'Beverages', order: 4 },
  ],
  products: [
    {
      id: 'prod_001',
      name: 'Caesar Salad',
      description: 'Fresh romaine lettuce with Caesar dressing, parmesan cheese, and croutons',
      price: 3500,
      available: true,
      stock: 15,
      categoryId: 'cat_001',
      imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400&h=300&fit=crop',
      preparationTime: 10,
      rating: 4.7,
      reviewCount: 23,
      discount: 0,
    },
    {
      id: 'prod_002',
      name: 'Grilled Chicken',
      description: 'Tender grilled chicken breast with herbs, served with vegetables and rice',
      price: 8500,
      available: true,
      stock: 8,
      categoryId: 'cat_002',
      imageUrl: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=400&h=300&fit=crop',
      preparationTime: 20,
      rating: 4.8,
      reviewCount: 45,
      discount: 10,
    },
    {
      id: 'prod_003',
      name: 'Chocolate Cake',
      description: 'Rich chocolate cake with ganache frosting and fresh berries',
      price: 4000,
      available: true,
      stock: 12,
      categoryId: 'cat_003',
      imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop',
      preparationTime: 5,
      rating: 4.9,
      reviewCount: 67,
      discount: 0,
    },
    {
      id: 'prod_004',
      name: 'Fresh Juice',
      description: 'Freshly squeezed orange juice, served cold',
      price: 2000,
      available: true,
      stock: 25,
      categoryId: 'cat_004',
      imageUrl: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=300&fit=crop',
      preparationTime: 3,
      rating: 4.5,
      reviewCount: 18,
      discount: 0,
    },
    {
      id: 'prod_005',
      name: 'French Onion Soup',
      description: 'Classic French onion soup with melted cheese and croutons',
      price: 4500,
      available: true,
      stock: 10,
      categoryId: 'cat_001',
      imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop',
      preparationTime: 15,
      rating: 4.6,
      reviewCount: 31,
      discount: 0,
    },
    {
      id: 'prod_006',
      name: 'Beef Steak',
      description: 'Premium beef steak cooked to perfection, served with roasted vegetables',
      price: 12000,
      available: false,
      stock: 0,
      categoryId: 'cat_002',
      imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop',
      preparationTime: 25,
      rating: 4.9,
      reviewCount: 89,
      discount: 15,
    },
    {
      id: 'prod_007',
      name: 'Tiramisu',
      description: 'Classic Italian dessert with coffee, mascarpone, and cocoa powder',
      price: 5000,
      available: true,
      stock: 6,
      categoryId: 'cat_003',
      imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit=crop',
      preparationTime: 5,
      rating: 4.8,
      reviewCount: 52,
      discount: 0,
    },
    {
      id: 'prod_008',
      name: 'Cappuccino',
      description: 'Rich espresso with steamed milk foam and cocoa powder',
      price: 2500,
      available: true,
      stock: 30,
      categoryId: 'cat_004',
      imageUrl: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&h=300&fit=crop',
      preparationTime: 5,
      rating: 4.7,
      reviewCount: 41,
      discount: 0,
    },
    {
      id: 'prod_009',
      name: 'Bruschetta',
      description: 'Toasted bread with fresh tomatoes, basil, and mozzarella',
      price: 3000,
      available: true,
      stock: 18,
      categoryId: 'cat_001',
      imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&h=300&fit=crop',
      preparationTime: 8,
      rating: 4.6,
      reviewCount: 27,
      discount: 0,
    },
    {
      id: 'prod_010',
      name: 'Salmon Fillet',
      description: 'Grilled salmon with lemon, herbs, and seasonal vegetables',
      price: 11000,
      available: true,
      stock: 5,
      categoryId: 'cat_002',
      imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&h=300&fit=crop',
      preparationTime: 22,
      rating: 4.8,
      reviewCount: 63,
      discount: 0,
    },
    {
      id: 'prod_011',
      name: 'Ice Cream Sundae',
      description: 'Vanilla ice cream with chocolate sauce, nuts, and cherry',
      price: 3500,
      available: true,
      stock: 20,
      categoryId: 'cat_003',
      imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=300&fit=crop',
      preparationTime: 3,
      rating: 4.5,
      reviewCount: 34,
      discount: 0,
    },
    {
      id: 'prod_012',
      name: 'Fresh Lemonade',
      description: 'Refreshing homemade lemonade with fresh mint',
      price: 2000,
      available: true,
      stock: 35,
      categoryId: 'cat_004',
      imageUrl: 'https://images.unsplash.com/photo-1523677011783-c91d1bbe2fdc?w=400&h=300&fit=crop',
      preparationTime: 2,
      rating: 4.4,
      reviewCount: 19,
      discount: 0,
    },
  ],
};

export const menuService = {
  async getMenu(restaurantId: string): Promise<MenuResponse> {
    try {
      const response = await apiClient.get<MenuResponse>(
        `/api/restaurants/${restaurantId}/menu`
      );
      return response.data;
    } catch (error) {
      // Return mock data if API fails
      console.warn('Using mock menu data');
      return MOCK_MENU_DATA;
    }
  },
};

